name: expandable_widgets
description: A package that provides expandable widgets for Flutter. Written in %100 Dart.
version: 1.0.0
homepage: https://github.com/fatihozkan-github/ExpandableWidgets.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/background.png